name: MLflow CI Training

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Install Python dependencies via pip (PALING SIMPLE)
      - name: Install MLflow and dependencies
        run: |
          pip install mlflow scikit-learn pandas numpy pandas seaborn matplotlib

      # 3. Run MLflow project (HARUS lengkap parameter)
      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . \
            -P data_path=diabetes_preprocessing.csv \
            -P test_size=0.2 \
            -P random_state=42 \
            --env-manager=local

      # 4. Upload MLflow artifacts
      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model_artifacts
          path: MLProject/mlruns
