name: MLflow CI

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train-log-and-dockerize:
    runs-on: ubuntu-latest

    steps:

    # 1. Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Install MLflow + dependencies
    - name: Install dependencies
      run: |
        pip install mlflow scikit-learn pandas numpy

    # 3. Run MLflow Project
    - name: Run MLflow Project
      run: |
        mlflow run MLProject --env-manager=local \
          -P data_path=diabetes_preprocessing.csv \
          -P test_size=0.2 \
          -P random_state=42

    # 4. Commit & push artifacts (optional for tugas)
    - name: Commit and push MLflow artifacts
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        git add MLProject/mlruns || true
        git add MLProject/mlflow.db || true
        git add mlflow.db || true

        git commit -m "Update MLflow artifacts" || true
        git push || true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    # 5. Ambil path model terbaru
    - name: Get latest MLflow model artifact path
      id: get_model_path
      run: |
        MODEL_PATH=$(find MLProject/mlruns -type d -path "*/artifacts/*" | sort -r | head -n 1)
        echo "MODEL_PATH=$MODEL_PATH" >> $GITHUB_ENV

    # 6. Login ke Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    # 7. Build Docker image dari model MLflow
    - name: Build Docker Image
      run: |
        mlflow models build-docker \
          -m "${{ env.MODEL_PATH }}" \
          -n "${{ secrets.DOCKER_HUB_USERNAME }}/msml-model"

    # 8. Push ke Docker Hub
    - name: Push Docker Image
      run: |
        docker push "${{ secrets.DOCKER_HUB_USERNAME }}/msml-model:latest"
